###########################################################################
#
# Generated by : Version 8.0 Build 231 07/10/2008 Service Pack 1 SJ Web Edition
#
# Project      : flashy_get
# Revision     : testingigo_all
#
# Date         : Thu Jul 31 11:34:57 AM Eastern Daylight Time 2008
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------

#
# Entity Specific Timing Assignments found in
# the Timing Analyzer Settings report panel
#
set_false_path -from [get_keepers {*dcfifo_d6f1*|delayed_wrptr_g[*]}] -to [get_keepers {*dcfifo_d6f1*|*rs_dgwp|*dffpipe8|dffe9a[*]}]
set_false_path -from [get_keepers {*dcfifo_d6f1*|rdptr_g[*]}] -to [get_keepers {*dcfifo_d6f1*|*ws_dgrp|*dffpipe11|dffe12a[*]}]


# ---------------------------------------------

